-- Grocery Parlour initial schema
create extension if not exists pgcrypto;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  image_url text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete restrict,
  name text not null,
  price numeric(10,2) not null check (price >= 0),
  stock integer not null check (stock >= 0),
  image_url text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  customer_email text,
  status text not null default 'New',
  item_count integer not null default 0,
  total numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  qty integer not null check (qty > 0),
  unit_price numeric(10,2) not null check (unit_price >= 0),
  line_total numeric(12,2) not null check (line_total >= 0),
  created_at timestamptz not null default now()
);

create index if not exists idx_products_category_id on public.products(category_id);
create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_order_items_order_id on public.order_items(order_id);

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

do $$ begin
  create policy "Public read categories" on public.categories for select using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Public read products" on public.products for select using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Public read orders" on public.orders for select using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Public read order items" on public.order_items for select using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Public write orders" on public.orders for insert with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Public write order items" on public.order_items for insert with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Public write categories" on public.categories for all using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Public write products" on public.products for all using (true) with check (true);
exception when duplicate_object then null; end $$;

